name: LaTeX compilation

#トリガーの設定？
on:
  push:
    branches:
      - main
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Merge main branch
        run: |
          git config user.name Shun2439
          git config user.email shunta.kobayashi24@gmail.com
          git checkout pdf
          git merge main

      - name: compile questions
        uses: dante-ev/latex-action@latest
        with:
          root_file: question.tex
          compiler: ptex2pdf
          args: -l

      - name: recompile questions
        uses: dante-ev/latex-action@latest
        with:
          root_file: question.tex
          compiler: ptex2pdf
          args: -l

      - name: compile answers
        uses: dante-ev/latex-action@latest
        with:
          root_file: ans.tex
          compiler: ptex2pdf
          args: -l

      - name: recompile answers
        uses: dante-ev/latex-action@latest
        with:
          root_file: ans.tex
          compiler: ptex2pdf
          args: -l

      - name: Push PDF file
        run: |
          git add .
          git commit -m ":white_check_mark: LaTeX compilation"
          git push origin pdf
